apiVersion: apps/v1
kind: Deployment
metadata:
  name: nust-scrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nust-scrapper
  template:
    metadata:
      labels:
        app: nust-scrapper
    spec:
      containers:
        - name: nust-scrapper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "-u", "scrapper.py"]
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: nust-scrapper-config
                  key: URL
            - name: SELECTOR
              valueFrom:
                configMapKeyRef:
                  name: nust-scrapper-config
                  key: SELECTOR
            - name: EXPECTED_TEXT
              valueFrom:
                configMapKeyRef:
                  name: nust-scrapper-config
                  key: EXPECTED_TEXT
            - name: NOTIFY_RUN_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nust-scrapper-config
                  key: NOTIFY_RUN_CHANNEL
            - name: INTERVAL_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: nust-scrapper-config
                  key: INTERVAL_MINUTES
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
