apiVersion: v1
kind: Service
metadata:
  name: nust-scrapper
spec:
  type: ClusterIP
  selector:
    app: nust-scrapper
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
