apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: diffbeep
spec:
  type: ClusterIP
  selector:
    app: diffbeep
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
